### ISSUE TITLE
Unable to download data from Amazon AWS server

### ISSUE THREAD

**Issue by hrushikeshloya** [rtu715/NAS-Bench-360#3]
Hi,

I was looking to download the NinaPro and DarcyFlow datasets for my NAS experiments but am receiving `HTTP request sent, awaiting response... 403 Forbidden` when I try `wget https://pde-xd.s3.amazonaws.com/piececonst_r421_N1024_smooth1.mat`. Is there something I'm missing in order to download the data?

Hrushi

**Comment by rtu715** [comment]
Hi Hrushi, we are in the process of changing the dataset's hosting so AWS might be temporarily unavailable. In the meantime, please use the datasets hosted on the shared drive here: https://drive.google.com/drive/folders/1OOp6UrCiP79mTIkCrUdjjHWDo8K0bJUw. 

You should be able to find the files for NinaPro and Darcyflow in their corresponding folders. Best of luck with your experiments.

Renbo
